# Generated by Django 3.2.23 on 2024-01-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lastemail_sleephrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(null=True)),
                ('ti', models.TimeField(null=True)),
                ('desc', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='lastemail',
        ),
        migrations.DeleteModel(
            name='sleephrs',
        ),
    ]
