# Generated by Django 3.2.23 on 2024-01-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240110_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='sleephrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sleephr', models.IntegerField()),
                ('d', models.DateTimeField()),
                ('day', models.CharField(max_length=30)),
            ],
        ),
    ]
